### ISSUE TITLE
App doesn't works

### ISSUE THREAD

**Issue by thahim** [googlecreativelab/lipswap#5]
When i snap a picture from camera, app crashes, when i select a picture from gallery the app doesn't shows that picture.

**Comment by trippedout** [comment]
Hi thahim - if you could please let me know what phone you are using, what version of android is currently installed (in settings > about phone) and if possible, respond to this with a bug report (using `adb bugreport` or clicking send bug report when it crashes), that would help so much :)

**Comment by thahim** [comment]
S6 edge+ android 6.0.1
