### ISSUE TITLE
Fails to save video

### ISSUE THREAD

**Issue by blowsie** [googlecreativelab/lipswap#6]
Device: SM-G850F
Device Name: Samsung Galaxy Alpha
OS: 5.0 Lollipop

When pushing the stop button after creating a video, a dialog shows saying "Can'y play this video"
I tried looking on the device storage for an output file but could not find anything

**Comment by trippedout** [comment]
Hi blowsie - can you make sure you are running the latest version (1.0.2) of the app? And if it continues to happen, if you could send/attach a bug report, that would be excellent, thanks!

**Comment by BraisGabin** [comment]
Same issue here. 
Nexus 5
Android 5.1.1
App 1.0.2

There is not crash to send a bug report. I can connect the adb to get the catlog if it's. Will it help?

**Comment by trippedout** [comment]
yes please - run the app to the point where it crashes, then type `adb bugreport | grep "androidexperiments.lipflip" > bugs.txt` and post results into a gist/online somewhere and link here

**Comment by BraisGabin** [comment]
I didn't know about `adb bugreport`. It's very handy. Here it's: https://gist.github.com/BraisGabin/01db882de9783c374fa1

**Comment by trippedout** [comment]
is it safe to say that you opened the app, clicked record, recorded for a few seconds, clicked stop, it trys to play, then cycles back to the first activity, and u tried again, a few times?

**Comment by BraisGabin** [comment]
Yes, I tried it more than 4 times for sure

**Comment by blowsie** [comment]
In my scenario;

> is it safe to say that you;
 - [x] opened the app
 - [x] clicked record
 - [x] recorded for a few seconds
 - [x] clicked stop <--------------------------- Crash takes place as soon as you click this
 - [ ] it trys to play
 - [ ] then cycles back to the first activity

**Comment by BraisGabin** [comment]
Well, I found a workaround that works for me. I was always selecting apps from the gallery and it fails.

I took a picture from the camara and after that both options worked.
